data:
    dataset: "BCP"
    data_path: "/public/home/wangkd2023/Denghw/diffsuion_code/1.txt"
    image_size: 224
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: false
    rescaled: false
    num_workers: 2
    num_time_type: 13
    latent_size:
        - 12
        - 15
        - 12

model:
    type: "simple"
    in_channels: 1
    out_ch: 1
    ch: 16
    ch_mult: [1, 2, 2, 4, 4]
    num_res_blocks: 1
    attn_resolutions: [14, ]
    cond_resolutions: [14, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.999
    ema: True
    resamp_with_conv: False

diffusion:
    beta_schedule: sigmoid
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    num_denoising_timesteps: 400

training:
    batch_size: 1
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 2000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0